# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:16
 
    steps:
      - checkout
      - run:
          name: Install Dependencies 
          command: |
            npm install --save
            
# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - heroku/deploy-via-git:
          filters:
              branches:
                only:
                  - master
          requires:
            - build